export const SITE = {
  name: "Wyper Window Cleaning",
  owner: "Brendan McGrath",
  phone: "519-820-8827",
  phoneHref: "tel:5198208827",
  email: "info@wyperwindowcleaning.ca",
  emailHref: "mailto:info@wyperwindowcleaning.ca",
  url: "https://wyperwindowcleaning.ca",
  domain: "wyperwindowcleaning.ca",
  logo: "/logos/mainlogo.png",
  logoDark: "/logos/mainlogodarky.png",
  region: "Ontario",
  country: "CA",
  priceRange: "$$",
  tagline: "Serving Guelph and Wellington County",
  areasServed: [
    "Guelph",
    "Fergus",
    "Elora",
    "Rockwood",
    "Cambridge",
  ] as const,
  openingHours: "Mo-Sa 08:00-18:00",
  nav: [
    { href: "/", label: "Home" },
    { href: "/services", label: "Services" },
    { href: "/service-area", label: "Service Area" },
    { href: "/about", label: "About" },
    { href: "/contact", label: "Contact" },
  ] as const,
} as const;
